"""initial_migration

Revision ID: eb23e8a7e7ac
Revises: 
Create Date: 2026-01-20 09:04:32.451349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb23e8a7e7ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'USUARIO', 'VIEWER', name='rol_usuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('MANIFIESTO', 'FACTURA', name='tipo_documento'), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PROCESANDO', 'COMPLETADO', 'ERROR', name='estado_documento'), nullable=False),
    sa.Column('tamaño', sa.BigInteger(), nullable=False),
    sa.Column('paginas', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('texto_extraido', sa.Boolean(), nullable=False),
    sa.Column('ocr_aplicado', sa.Boolean(), nullable=False),
    sa.Column('error_procesamiento', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_estado'), 'documentos', ['estado'], unique=False)
    op.create_index(op.f('ix_documentos_nombre'), 'documentos', ['nombre'], unique=False)
    op.create_index(op.f('ix_documentos_tipo'), 'documentos', ['tipo'], unique=False)
    op.create_index(op.f('ix_documentos_usuario_id'), 'documentos', ['usuario_id'], unique=False)
    op.create_table('busquedas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PROCESANDO', 'COMPLETADO', 'ERROR', name='estado_busqueda'), nullable=False),
    sa.Column('busqueda_fuzzy', sa.Boolean(), nullable=False),
    sa.Column('normalizar_codigos', sa.Boolean(), nullable=False),
    sa.Column('codigos_buscados', sa.Integer(), nullable=False),
    sa.Column('codigos_encontrados', sa.Integer(), nullable=False),
    sa.Column('codigos_no_encontrados', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_mensaje', sa.Text(), nullable=True),
    sa.Column('manifiesto_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manifiesto_id'], ['documentos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_busquedas_estado'), 'busquedas', ['estado'], unique=False)
    op.create_index(op.f('ix_busquedas_manifiesto_id'), 'busquedas', ['manifiesto_id'], unique=False)
    op.create_index(op.f('ix_busquedas_usuario_id'), 'busquedas', ['usuario_id'], unique=False)
    op.create_table('codigos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('codigo_normalizado', sa.String(length=100), nullable=False),
    sa.Column('pagina', sa.Integer(), nullable=False),
    sa.Column('linea', sa.Integer(), nullable=True),
    sa.Column('posicion_x', sa.Float(), nullable=True),
    sa.Column('posicion_y', sa.Float(), nullable=True),
    sa.Column('ancho', sa.Float(), nullable=True),
    sa.Column('alto', sa.Float(), nullable=True),
    sa.Column('contexto', sa.Text(), nullable=True, comment='Texto alrededor del código para contexto'),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codigos_codigo'), 'codigos', ['codigo'], unique=False)
    op.create_index(op.f('ix_codigos_codigo_normalizado'), 'codigos', ['codigo_normalizado'], unique=False)
    op.create_index(op.f('ix_codigos_documento_id'), 'codigos', ['documento_id'], unique=False)
    op.create_index(op.f('ix_codigos_pagina'), 'codigos', ['pagina'], unique=False)
    op.create_table('reportes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'GENERANDO', 'COMPLETADO', 'ERROR', name='estado_reporte'), nullable=False),
    sa.Column('color_resaltado', sa.Enum('AMARILLO', 'VERDE', 'AZUL', 'ROJO', 'NARANJA', 'ROSA', name='color_resaltado'), nullable=False),
    sa.Column('incluir_no_encontrados', sa.Boolean(), nullable=False),
    sa.Column('agregar_marca_agua', sa.Boolean(), nullable=False),
    sa.Column('pdf_disponible', sa.Boolean(), nullable=False),
    sa.Column('excel_disponible', sa.Boolean(), nullable=False),
    sa.Column('csv_disponible', sa.Boolean(), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('excel_path', sa.String(length=500), nullable=True),
    sa.Column('csv_path', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_mensaje', sa.Text(), nullable=True),
    sa.Column('busqueda_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['busqueda_id'], ['busquedas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reportes_busqueda_id'), 'reportes', ['busqueda_id'], unique=False)
    op.create_index(op.f('ix_reportes_estado'), 'reportes', ['estado'], unique=False)
    op.create_table('resultados_busqueda',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_original', sa.String(length=100), nullable=False),
    sa.Column('codigo_normalizado', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.Enum('ENCONTRADO', 'NO_ENCONTRADO', 'PARCIAL', name='estado_resultado'), nullable=False),
    sa.Column('frecuencia', sa.Integer(), nullable=False),
    sa.Column('ubicaciones', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array de {documento_id, pagina, contexto}'),
    sa.Column('similares', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array de códigos similares encontrados'),
    sa.Column('busqueda_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['busqueda_id'], ['busquedas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resultados_busqueda_busqueda_id'), 'resultados_busqueda', ['busqueda_id'], unique=False)
    op.create_index(op.f('ix_resultados_busqueda_codigo_normalizado'), 'resultados_busqueda', ['codigo_normalizado'], unique=False)
    op.create_index(op.f('ix_resultados_busqueda_codigo_original'), 'resultados_busqueda', ['codigo_original'], unique=False)
    op.create_index(op.f('ix_resultados_busqueda_estado'), 'resultados_busqueda', ['estado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resultados_busqueda_estado'), table_name='resultados_busqueda')
    op.drop_index(op.f('ix_resultados_busqueda_codigo_original'), table_name='resultados_busqueda')
    op.drop_index(op.f('ix_resultados_busqueda_codigo_normalizado'), table_name='resultados_busqueda')
    op.drop_index(op.f('ix_resultados_busqueda_busqueda_id'), table_name='resultados_busqueda')
    op.drop_table('resultados_busqueda')
    op.drop_index(op.f('ix_reportes_estado'), table_name='reportes')
    op.drop_index(op.f('ix_reportes_busqueda_id'), table_name='reportes')
    op.drop_table('reportes')
    op.drop_index(op.f('ix_codigos_pagina'), table_name='codigos')
    op.drop_index(op.f('ix_codigos_documento_id'), table_name='codigos')
    op.drop_index(op.f('ix_codigos_codigo_normalizado'), table_name='codigos')
    op.drop_index(op.f('ix_codigos_codigo'), table_name='codigos')
    op.drop_table('codigos')
    op.drop_index(op.f('ix_busquedas_usuario_id'), table_name='busquedas')
    op.drop_index(op.f('ix_busquedas_manifiesto_id'), table_name='busquedas')
    op.drop_index(op.f('ix_busquedas_estado'), table_name='busquedas')
    op.drop_table('busquedas')
    op.drop_index(op.f('ix_documentos_usuario_id'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_tipo'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_nombre'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_estado'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
