// Pages - Páginas de la aplicación
export { DocumentosPage } from './DocumentosPage'
export { CargarPage } from './CargarPage'
export { BusquedaPage } from './BusquedaPage'
export { ResaltarPage } from './ResaltarPage'
export { VisorPage } from './VisorPage'
export { ReportesPage } from './ReportesPage'
export { ConfiguracionPage } from './ConfiguracionPage'
export { ClientesPage } from './ClientesPage'
export { InventarioPage } from './InventarioPage'
export { PedidosPage } from './PedidosPage'
export { FacturasPage } from './FacturasPage'
export { LoginPage } from './LoginPage'
export { UsuariosPage } from './UsuariosPage'
